# Generated by Django 5.2.6 on 2025-09-15 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_attendance'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='score',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
